use_frameworks!

target 'PodSpecRepertory_Example' do
  pod 'PodSpecRepertory', :path => '../'

  target 'PodSpecRepertory_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
